// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4fc4h-t2U9PBnVigWXvHtpqrrPSmFRYM',
    appId: '1:74353795008:web:98e38c439803edaa8d3225',
    messagingSenderId: '74353795008',
    projectId: 'mycareteam-44a5e',
    authDomain: 'mycareteam-44a5e.firebaseapp.com',
    storageBucket: 'mycareteam-44a5e.appspot.com',
    measurementId: 'G-GVRCDT7LL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4dk-8ALdo7bN8ztYd0vyHk04QGPm59_g',
    appId: '1:74353795008:android:c0998b4f9b292cee8d3225',
    messagingSenderId: '74353795008',
    projectId: 'mycareteam-44a5e',
    storageBucket: 'mycareteam-44a5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfLoCsGB4nIH2T1qfZnBRtnYjCYCzHt5M',
    appId: '1:74353795008:ios:a159a9a975cd2bae8d3225',
    messagingSenderId: '74353795008',
    projectId: 'mycareteam-44a5e',
    storageBucket: 'mycareteam-44a5e.appspot.com',
    iosBundleId: 'com.example.mycareteam',
  );
}
